### ISSUE TITLE
Product model not enqueued if modified

### ISSUE THREAD

**Issue by mmenozzi** [webgriffe/SyliusAkeneoPlugin#102]
It seems that if someone modify a product model on Akeneo (without changing any variant-specific attribute, only model ones) the related variant products are not enqueued byt the Product importer.

Maybe is because in such situation Akeneo APIs do not return variants (products) as modified since the given date. Only parent product (product model). If this is the case, here:

https://github.com/webgriffe/SyliusAkeneoPlugin/blob/9782b54ff560edf1aa36eca5d34e0ba8e9162200/src/Product/Importer.php#L166-L180

We should also enqueue products of those product models modified since the given date.

**Comment by mmenozzi** [comment]
Maybe this could be resolved with #157

**Comment by lruozzi9** [comment]
> Maybe this could be resolved with #157

Nope.

But I suggest adding a new ProductModel importer. This product model importer should dispatch N product import messages for any product in the product model. This will also solve a bug in the current version. If you submit the import of a product in the admin only the variants already existing in Sylius will be imported, not all the products on Akeneo!
