### ISSUE TITLE
It should be possible to configure the locale mapping between Akeneo and Sylius

### ISSUE THREAD

**Issue by Jashi** [webgriffe/SyliusAkeneoPlugin#120]
Hi,
we are using languages as locales in Sylius (en, de, ...) instead of en_US, de_DE, ... as Akeneo requires.
Right now I did not find a possibility to configure a mapping between these. Did I miss something? 
We discussed this class in Slack yesterday: https://github.com/synolia/SyliusAkeneoPlugin/blob/master/src/Provider/SyliusAkeneoLocaleCodeProvider.php but as far as I see it, it's impossible to override/circumvent as it's final and hardcoded into several other class constructors

If this is something that you think could be implemented we'd be glad to try it. We're just not sure what the best way to go about it would be (using an interface everywhere as type hint instead of the class itself maybe). And most importantly: is this even the one place that does all the locale mapping between the system?

**Comment by mmenozzi** [comment]
Hi @Jashi, are you aware that this is the repository of the **Webgriffe** SyliusAkeneoPlugin and not the Synolia one?

**Comment by Jashi** [comment]
Nope, thanks - closing it.
