### ISSUE TITLE
Clean attributes by inline style

### ISSUE THREAD

**Issue by lruozzi9** [webgriffe/SyliusAkeneoPlugin#163]
Akeneo uses for his WYSIWYG inline styles instead of HTML attributes like strong/i/etc. This could lead to an inconsistent style on the website.
It would be nice to have these inline styles removed in favor of HTML attributes.
Anyway, this feature should be easily toggleable, so if someone would not have this cleaning, they could skip it.

**Comment by mmenozzi** [comment]
We decided that this is not a responsibility of this plugin.
