### ISSUE TITLE
Split TranslatablePropertyValueHandler

### ISSUE THREAD

**Issue by mmenozzi** [webgriffe/SyliusAkeneoPlugin#3]
The `TranslatablePropertyValueHandler` currently sets property value on both `ProductVariantTranslation` and `ProductTranslation`.

Given the fact that there could be more than one value handler for each Akeneo value, it should be split into two separate value handlers: `ProductTranslationPropertyValueHandler` and `ProductVariantTranslationPropertyValueHandler`.

**Comment by lruozzi9** [comment]
@mmenozzi is this issue still open? I mean: are we sure we want to split the value handler? The current implementation with the PropertyAccessor looks good to me.

**Comment by mmenozzi** [comment]
I don't remember what was the issue here. I'm going to close this.
