### ISSUE TITLE
Add retry counter to queue

### ISSUE THREAD

**Issue by aleho** [webgriffe/SyliusAkeneoPlugin#35]
On busy sites a failure might actually be retryable (deadlocks come to mind) and could already work a few seconds later.

The current implementation will try forever (even for items that are likely to never succeed), which on the other hand makes sense considering that the enqueue command with since-file cannot check for "changed after date X or not yet imported".

In my opinion a retry stategy (something like Symfony's `RetryStrategyInterface`) might still come in handy.

What do you think?

**Comment by mmenozzi** [comment]
I think that if we need this kind of logic maybe it's better to refactor the plugin to fully use/support [Symfony's Messenger](https://symfony.com/doc/current/messenger.html) component for the whole queue handling.

@fabianaromagnoli @LucaGallinari @lruozzi9 what do you think?

**Comment by aleho** [comment]
Because I really love the messenger and also it's implementation: Absolutely!

You should still keep the queue though and mark entries done in message handlers because there's not good way of checking for "item done" in messenger, especially once you start using an external queue system like RabbitMQ.

**Comment by lruozzi9** [comment]
With the v2.0 we have introduced Messenger to handle the QueueItem to import, so the scope of the issue should be completed.

> You should still keep the queue though and mark entries done in message handlers because there's no good way of checking for "item done" in messenger, especially once you start using an external queue system like RabbitMQ.

Obviously, without storing the imported items in the queue we can't display the status of the imports, but keeping the current queue only for this scope smell. I am thinking to add something like a new entity that will contain the identifier of the product and some other info like the Akeneo attributes used to populate the product. Another solution could be simply adding a column importedAt on the ProductVariant with the timestamp of the last import from Akeneo. Anyway, this will be done in another issue.
