### ISSUE TITLE
Refresh Akeneo API access token when it has expired

### ISSUE THREAD

**Issue by fabianaromagnoli** [webgriffe/SyliusAkeneoPlugin#37]
Method \Webgriffe\SyliusAkeneoPlugin\ApiClient::authenticatedRequest makes login only if token is not set. But the Akeneo API access token has a lifetime (3600 seconds) and when it is expired the request responds with a 401 error.
If you have hundreds of products on Akeneo, and you run all importers for all products, this is likely to happen. In this case the importer stops with this error:

<img width="877" alt="Screenshot 2021-01-26 at 20 46 41" src="https://user-images.githubusercontent.com/23638004/105962470-27846300-6080-11eb-8cf1-ee2c1589a480.png">

The ApiClient should handle this case and login again, or even better, according to oauth protocol, il should refresh the access token using the refresh token.

**Comment by mmenozzi** [comment]
Done in #39. Closing.
