### ISSUE TITLE
Can't know the source of a product event

### ISSUE THREAD

**Issue by aleho** [webgriffe/SyliusAkeneoPlugin#48]
At the moment there's no way to find the source of a `sylius.product.*` event.

In my use case I'd like to be able to know that the Akeneo importer dispatched it, so I can handle only those (especially ensuring some default values are set on import, which might get overridden by the user).

If you think this would be a good addition, I could provide a PR.

**Comment by mmenozzi** [comment]
Yes thank you! I’d dispatch a separate pre and post event dedicated to the Akeneo import.
