### ISSUE TITLE
Import fails trying to create empty translation

### ISSUE THREAD

**Issue by aleho** [webgriffe/SyliusAkeneoPlugin#62]
Since commit bbaecd16e84b5d653a001ba6e06bde2c63748114 import fails with:

```
[Doctrine\DBAL\Exception\NotNullConstraintViolationException]
An exception occurred while executing 'INSERT INTO sylius_product_translation (name, slug, description, meta_keywords, meta_description, short_description, locale, translatable_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params [null, null, null, null, null, null, "en_US", 3755]:

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null
```

Reverting bbaecd16e84b5d653a001ba6e06bde2c63748114 "fixes" the problem.

Any ideas what's going on?

**Comment by mmenozzi** [comment]
Yes. It's because now the plugin properly imports attributes that have been emptied on Akeneo. So if you have at least one empty attribute imported with the `TranslatablePropertyValueHandler`, now the plugin creates the translations for all languages to be able to set `null` on that property. So now it fails if you have untranslated products on Akeneo (at least for the not nullable properties).

A quick solution to this is to implement a listener on the product.pre_create/update event which removes empty translations before saving.

Another solution it could be to not create the translation in the `TranslatablePropertyValueHandler` if the value is null.

What do you think? We're open to suggestions.

**Comment by aleho** [comment]
In my opinion I would not create a translation if it cannot be created with valid data.

In a setup where the default locale is X and there's also "optional" locales A, B, C, a missing translation leads to a failed import (even though the data is "valid" in Akeneo).

So, I'd not create the translation at all.

**Comment by mmenozzi** [comment]
Yes sounds good. Feel free to provide a PR if you need this fix soon. Anyway we’ll do our best to fix this issue ASAP.

**Comment by mmenozzi** [comment]
Hi @aleho,
have a look at the #63 PR for this issue.
Let me know what do you think.

**Comment by aleho** [comment]
Sorry, there was a lot going on and I couldn't get the import to run.

Apparently if `productVariants` on `$existentProductImage` is null (ImageValueHandler:104) the check `hasProductVariant` fails completely. It should be set in the constructor, but apparently that's never called for existing entities.

What's especially odd here: `$existentProductImage instanceof Sylius\Component\Core\ModelProductImage`, even though Sylius is set up and configured correctly and the entity has not been touched:

```shell
$ console debug:container --parameter=sylius.model.product_image.class
 ---------------------------------- --------------------------------- 
  Parameter                          Value                            
 ---------------------------------- --------------------------------- 
  sylius.model.product_image.class   App\Entity\Product\ProductImage  
 ---------------------------------- --------------------------------- 
```

So I couldn't even override the method in there to check of the collection to do a temporary check like `return($this->productVariants && parent::hasProductVariant($productVariant));`.

What's wrong there?

**Comment by mmenozzi** [comment]
@aleho we never had this issue. Btw I don't think it's related to empty translations.

**Comment by aleho** [comment]
It only happens since `bbaecd16e84b5d653a001ba6e06bde2c63748114`. Haven't had time to investigate, but a clean import and subsequent update fails and can be reproduced here.

I'll try to get more details as soon as possible.

**Comment by mmenozzi** [comment]
Ok thank you. Please, when you'll have further details open a new issue for the ImageValueHandler bug.

This one is for empty translations (so the TranlsatablePropertyValueHandler).

**Comment by aleho** [comment]
You're right. I suspected the commit being the culprit for the other problem too (but should have opened a separate issue anyway).

Turns out, FriendsOfSylius/SyliusImportExportPlugin overrides the configuration in a very unexpected way.

Sorry for the noise, just thought to comment this here for the sake of completeness.

**Comment by mmenozzi** [comment]
Thank you for the update @aleho !
