### ISSUE TITLE
Impossible to retrieve a product with / in code

### ISSUE THREAD

**Issue by lruozzi9** [webgriffe/SyliusAkeneoPlugin#87]
The URL resolver's urlencode() function to get product information will also encode the slash (/) causing a 404. The Akeneo APIs expect in fact the code with slash not encoded.

**Comment by lruozzi9** [comment]
Hi @aleho! Since you've encountered a similar problem before (#52), did you also have this slash problem?

**Comment by aleho** [comment]
Wow, no, that's seems pretty special. For us it was only the special characters that are part of an URL that didn't work.

Which URLs are you talking about in detail?
Normally the "argument" part of the URL should not be in the product code, right?

Does this work as expected with the official API client?

**Comment by lruozzi9** [comment]
For example: in Akeneo we have a product with the code `ABCD/1-2`.The actual ApiClient will encode the product code in

**Comment by lruozzi9** [comment]
For example: in Akeneo we have a product with the code `ABC/1-2`.
The actual ApiClient will encode the product code in `ABC%2F1-2`, but the Akeneo get product API method will return 404 with the URL `{{host}}/api/rest/v1/products/ABC%2F1-2`.
Instead, encoding the code excepting the slash character (`ABC/1-2`) will return the correct product response.
I tried this directly making API requests in Akeneo v.4 and also in v.5.

**Comment by aleho** [comment]
Doesn't that seem wrong? It's either an endpoint or a parameter, but both?

Well, maybe `urlencode` cannot be used after all? Maybe only the '#` has to be encoded?
